platform :ios, '13.0'

# Specify target
target 'EcommerceApp' do
  use_frameworks!

  # Pods for EcommerceApp
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 7.0'
  pod 'RealmSwift', '~> 10.15'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  # Additional dependencies
  pod 'Stripe', '~> 22.0'
  pod 'AFNetworking', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  
  target 'EcommerceAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 4.0'
    pod 'Nimble', '~> 9.0'
  end

  target 'EcommerceAppUITests' do
    # Pods for UI testing
    pod 'EarlGrey', '~> 2.0'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end