apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 8080  # Port on the pod where the container is running
  type: ClusterIP