version: 1
formatters:
  simpleFormatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailedFormatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailedFormatter
    filename: /var/log/ecommerce/application.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  errorFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailedFormatter
    filename: /var/log/ecommerce/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  ecommerceLogger:
    level: DEBUG
    handlers: [consoleHandler, fileHandler, errorFileHandler]
    propagate: no

root:
  level: WARNING
  handlers: [consoleHandler]

disable_existing_loggers: false