name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push API Service Docker Image
      run: |
        docker build -t website/api-service:latest -f docker/Dockerfile.api .
        docker push website/api-service:latest

    - name: Build and Push Frontend Service Docker Image
      run: |
        docker build -t website/frontend-service:latest -f docker/Dockerfile.frontend .
        docker push website/frontend-service:latest

    - name: Deploy to Kubernetes Cluster
      uses: azure/k8s-deploy@v4
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          website/api-service:latest
          website/frontend-service:latest

    - name: Notify Success
      uses: actions/github-script@v6
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            body: "Deployment successful! :rocket:"
          })